import { StyleSheet } from "react-native";
import { RFPercentage } from "react-native-responsive-fontsize";

export default StyleSheet.create({
  background: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DFDFDF",
  },
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#c8f1ff",
    width: "90%",
    borderRadius: 15,
    borderWidth: 2,
    borderColor: "#004A85",
    marginTop: "1%",
    marginBottom: "5%",
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
  },
  container3: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DFDFDF",
    width: "95%",
    borderRadius: 15,
    borderWidth: 2,
    borderColor: "#004A85",
    marginTop: "1%",
    marginBottom: "5%",
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
  },
  titulo: { 
    padding: 10, 
    fontWeight: "bold", 
    textAlign: "center",
    fontSize: RFPercentage(3),
  },
  Logo: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: "10%",
  },
  login: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  input: {
    backgroundColor: "#F5F5F5",
    width: "90%",
    marginBottom: 15,
    color: "#000000",
    fontSize: RFPercentage(2),
    borderRadius: 10,
    borderWidth: 0.5,
    padding: 10,
    borderColor: "#004A85",
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.58,
    shadowRadius: 5,
    elevation: 10,
  },
  DropdownStyle: {
    backgroundColor: "#ffffff",
    height: 125,
    color: "#000000",
    fontSize: 17,
    borderRadius: 10,
    borderColor: "#004A85",
    borderWidth: 1,
  },
  drop: {
    backgroundColor: "#F5F5F5",
    width: "80%",
    marginBottom: 15,
    color: "#000000",
    fontSize: 17,
    borderRadius: 10,
    borderColor: "#004A85",
    borderWidth: 1,
    padding: 10,
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.37,
    shadowRadius: 7.49,
    elevation: 12,
  },
  cardsH: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    marginTop: "3%",
  },
  cardH: {
    backgroundColor: "#ffffff",
    alignItems: "center",
    padding: 10,
    maxWidth: "30%",
    maxHeight: 150,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowOpacity: 0.75,
    shadowRadius: 5,
    margin: "5%",
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#004A85",
  },
  icon: {
    textAlign: "center",
    padding: "20%",
  },
  btn: {
    backgroundColor: "#004A85",
    width: "90%",
    height: 45,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  btn2: {
    width: "90%",
    height: 45,
    alignItems: "center",
    justifyContent: "center",
  },
  txt: {
    fontSize: RFPercentage(2),
    textAlign: "center",
    alignSelf: "center",
  },
  info: {
    fontSize: RFPercentage(2),
    textAlign: "center",
    alignSelf: "center",
    marginLeft: "1%",
  },
  textBtn: {
    color: "#ffffff",
    textAlign: "center",
    fontSize: RFPercentage(2),
  },
  textBtn2: {
    color: "#ffffff",
    fontSize: RFPercentage(2),
    padding: 5,
  },
  linha: {
    flexDirection: "row",
    width: "100%",
  },
  coluna: {
    flexDirection: "column",
    alignSelf: "flex-start",
    width: "100%",
    paddingTop: 5,
  },
  cardAct: {
    alignSelf: "flex-end",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: "#004A85",
  },
  btncard: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    elevation: 3,
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 15,
    borderWidth: 2,
    borderColor: "#004A85",
    padding: 5,
    width: "100%",
  },
  flatList: {
    width: "90%",
  },
});
